# Sequel Database Configuration

connection: &connection
  host: localhost
  adapter: postgres
  encoding: unicode
  username: mtwtfss

development:
  <<: *connection
  database: bidbros_dev

test:
  <<: *connection
  database: bidbros_test

production:
  <<: *connection
  database: bidbros
